### ISSUE TITLE
Ajouter des label text avec les champs de saisie

### ISSUE THREAD

**Issue by sbonnand-perso** [jiemeb/CompteCible#1]
Sur la fenetre de configuration de concours, il faudrait ajouter des textes associés aux champs de saisie afin de savoir de quoi on parle.

**Comment by jiemeb** [comment]
Des Hints ont été ajouté sur ces fenetres de saisie. Ils donnent la signification quand les  champs sont vides

**Comment by sbonnand-perso** [comment]
cool, bonne solution !
il manque le hint sur le nom de l'archer par contre

![image](https://user-images.githubusercontent.com/63849397/80454181-f11b8b00-8929-11ea-8554-1c9d974dfb7d.png)

**Comment by sbonnand-perso** [comment]
screenshot avec la dernière version, celle du 27/04/2020 : 

Est il possible de faire défiler le texte dans les cases ? Avec l'affichage vertical, le texte du champ "volée"  n'est pas complet

![image](https://user-images.githubusercontent.com/63849397/80454965-2ffe1080-892b-11ea-8a7b-a48c63f888c0.png)
