### ISSUE TITLE
avoir le numéro de version

### ISSUE THREAD

**Issue by sbonnand-perso** [jiemeb/CompteCible#3]
il faudrait l'information du numéro de version quelque part ...

**Comment by jiemeb** [comment]
Integré dans la version 1.2.4

**Comment by jiemeb** [comment]
Integré grace aux api google. recuperation de la version dans Build.gradle:
       PackageManager manager = getApplicationContext().getPackageManager();
            PackageInfo info = null;
            info = manager.getPackageInfo( getApplicationContext().getPackageName(), 0);
             version += info.versionName;
